from dataclasses import dataclass
from typing import List, Optional, overload, Dict
from datetime import datetime
from abc import ABC, abstractmethod

@dataclass
class Residue:
    sequenceIndex: int
    """Index of amino acid in the sequence; ***0-indexed***"""
    structureIndex: int
    """Index of amino acid in the structure"""

@dataclass
class BindingSite:
    id: str
    confidence: float
    """Interval [0,1]; confidence is 1 for experimentally determined binding sites"""
    residues: List[Residue]
    """List of residues in the binding site; """

@dataclass
class SimilarSequenceAlignmentData:
    querySeqAlignedPartStartIdx: int
    """Index of amino acid in the sequence of query protein; ***0-indexed***"""
    querySeqAlignedPartEndIdx: int
    """Index of amino acid in the sequence of query protein; ***0-indexed***"""
    querySeqAlignedPart: str
    similarSequence: str
    similarSeqAlignedPartStartIdx: int
    """Index of amino acid in the sequence of similar protein; ***0-indexed***"""
    similarSeqAlignedPartEndIdx: int
    """Index of amino acid in the sequence of similar protein; ***0-indexed***"""
    similarSeqAlignedPart: str

@dataclass
class SimilarProtein:
    pdbId: str
    chain: str
    sequence: str
    pdbUrl: str
    tmScore: float
    bindingSites: List[BindingSite]
    alignmentData: SimilarSequenceAlignmentData
    seqToStrMapping: Dict[str, int]

@dataclass
class Metadata:
    dataSource: str
    timestamp: str  # ISO 8601 format

@dataclass
class ProteinData:
    id: str
    """ID generated by the application"""
    chain: str
    sequence: str
    pdbUrl: str
    bindingSites: List[BindingSite]
    metadata: Metadata
    similarProteins: Optional[List[SimilarProtein]] = None

class ProteinBuilderBase(ABC):
    def __init__(self, sequence: str, chain: str, pdb_url: str):
        self._sequence = sequence
        self._chain = chain
        self._pdb_url = pdb_url
        self._binding_sites = []

    @overload
    def add_binding_site(self, binding_site: BindingSite):
        self._binding_sites.append(binding_site)
        return self
    
    @overload
    def add_binding_site(self, id: str, confidence: float, residues: List[int]):
        self._binding_sites.append(BindingSite(id, confidence, residues))
        return self

    def add_binding_site(self, *args):
        if isinstance(args[0], BindingSite):
            self._binding_sites.append(args[0])
        elif len(args) == 3 and isinstance(args[0], str) and isinstance(args[1], float) and isinstance(args[2], list):
            self._binding_sites.append(BindingSite(args[0], args[1], args[2]))
        else:
            raise TypeError("Invalid arguments for add_binding_site")

        return self
    
    @abstractmethod
    def build(self):
        pass

class SimilarProteinBuilder(ProteinBuilderBase):
    def __init__(self, pdb_id: str, sequence: str, chain: str, pdb_url: str, tm_score: float):
        super().__init__(sequence, chain, pdb_url)
        self._pdb_id = pdb_id
        self._tm_score = tm_score
        self._alignment_data = None
        self.seq_to_str_mapping = {}

    def set_alignment_data(self, query_start: int, query_end: int, query_part: str, 
                           similar_seq: str, similar_start: int, similar_end: int, similar_part: str):
        self._alignment_data = SimilarSequenceAlignmentData(
            querySeqAlignedPartStartIdx=query_start,
            querySeqAlignedPartEndIdx=query_end,
            querySeqAlignedPart=query_part,
            similarSequence=similar_seq,
            similarSeqAlignedPartStartIdx=similar_start,
            similarSeqAlignedPartEndIdx=similar_end,
            similarSeqAlignedPart=similar_part
        )
        return self
    
    def set_seq_to_str_mapping(self, mapping: dict):
        self.seq_to_str_mapping = mapping
        return self

    def build(self) -> SimilarProtein:
        if not self._alignment_data:
            raise ValueError("Alignment data must be set before building SimilarProtein")
        
        if not self.seq_to_str_mapping:
            raise ValueError("Sequence to structure index mapping must be set before building SimilarProtein")
        
        return SimilarProtein(
            pdbId=self._pdb_id,
            chain=self._chain,
            sequence=self._sequence,
            pdbUrl=self._pdb_url,
            tmScore=self._tm_score,
            bindingSites=self._binding_sites,
            alignmentData=self._alignment_data,
            seqToStrMapping=self.seq_to_str_mapping
        )

class ProteinDataBuilder(ProteinBuilderBase):
    def __init__(self, id: str, chain: str, sequence: str, pdb_url: str):
        super().__init__(sequence, chain, pdb_url)
        self._id = id
        self._similar_proteins = []
        self._similar_protein_keys = set()
        self._metadata = None

    def add_similar_protein(self, similar_protein: SimilarProtein):
        key = (similar_protein.pdbId, similar_protein.chain)
        if key in self._similar_protein_keys: # We dont want to add the same similar protein twice
            return self
        self._similar_proteins.append(similar_protein)
        self._similar_protein_keys.add(key)
        return self

    def add_metadata(self, data_source: str, timestamp: Optional[str] = None):
        if timestamp is None:
            timestamp = datetime.now().isoformat()
        self._metadata = Metadata(dataSource=data_source, timestamp=timestamp)
        return self

    def build(self) -> ProteinData:
        if not self._metadata:
            raise ValueError("Metadata must be set before building ProteinData")
        
        return ProteinData(
            id=self._id,
            sequence=self._sequence,
            chain=self._chain,
            pdbUrl=self._pdb_url,
            bindingSites=self._binding_sites,
            metadata=self._metadata,
            similarProteins=self._similar_proteins if self._similar_proteins else None,
        )
